export const actionType = {
  // User
  SET_SIGN_IN: "SET_SIGN_IN",
  SET_SIGN_UP: "SET_SIGN_UP",
  SET_ME: "SET_ME",

  // Jobs
  SET_LIST_JOBS: "SET_LIST_JOBS",
  SET_TITLE_JOBS: "SET_TITLE_JOBS",
  SET_SUB_TYPE_JOBS: "SET_SUB_TYPE_JOBS",

  SET_TEST: "SET_TEST",
  IS_LOADING: "IS_LOADING",
  SET_PAGINATION: "SET_PAGINATION"
};
