export const actionType = {
  // User
  SET_SIGN_IN: "SET_SIGN_IN",
  SET_SIGN_UP: "SET_SIGN_UP",
  SET_ME: "SET_ME",
  SET_USER_INFO: "SET_USER_INFO",

  // Jobs
  SET_LIST_JOBS: "SET_LIST_JOBS",
  SET_TITLE_JOBS: "SET_TITLE_JOBS",
  SET_SUB_TYPE_JOBS: "SET_SUB_TYPE_JOBS",
  SET_LIST_TYPE_JOBS: 'SET_LIST_TYPE_JOBS',
  SEARCH_JOBS: 'SEARCH_JOBS',
  SET_DETAIL: 'SET_DETAIL',

  // Other
  IS_LOADING: "IS_LOADING",
  SET_PAGINATION: "SET_PAGINATION"
};
